const views = {
  reagent: "reagents",
  study: "studies",
  pack: "packs",
  price: "prices",
  promo: "promos",
  loyalty: "loyalties",
  proceeding: "expedientes",
  route: "routes",
  appointment: "appointments",
  request: "requests",
  quotation: "cotizacion",
  report: "reportes",
  cash: "cash",
  sampling: "samplings",
  routeTracking: "segRutas",
  shipmenttracking: "ShipmentTracking",
  recivetracking: "receiveTracking",
  workLists: "workLists",
  resultValidation: "ResultValidation",
  relaseValidation: "RelaseResult",
  invoiceCatalog: "invoiceCatalog",
  reportStudy: "reportstudy",
  parameters: "parameters",
  notifications:"notifications",
};

export default views;
