const views = {
  reagent: "reagents",
  study: "studies",
  pack: "packs",
  price: "prices",
  promo: "promos",
  loyalty: "loyalties",
  proceeding: "expedientes",
  route: "routes",
  appointment: "appointments",
  request: "requests",
  quotation: "cotizacion",
  report: "reportes",
  cash: "cash",
  sampling: "samplings",
  routeTraking: "segRutas",
  shipmenttracking: "ShipmentTracking",
  recivetracking: "ReciveTracking",
  workLists: "workLists",
  resultValidation: "ResultValidation",
  relaseValidation: "RelaseResult",
  invoiceCatalog: "invoiceCatalog",
  reportStudy: "reportstudy",
  parameters: "parameters",
};

export default views;
